### ISSUE TITLE
Facing build error with System.Net.IMAP4 in Azure DevOps

### ISSUE THREAD

**Issue by ashokkumarg** [bizzehdee/System.Net.Imap4#2]
I have a C# project in my local and it is working perfectly in my local machine. When I try to build the same project through Azure DevOps it gives the following build error

> **[error]d:\a\1\s\packages\System.Net.Imap4.0.1.0\System.Net.Imap4.sln.metaproj(0,0): Error MSB3202: The project file "d:\a\1\s\packages\System.Net.Imap4.0.1.0..\example\example.csproj" was not found.** d:\a\1\s\packages\System.Net.Imap4.0.1.0\System.Net.Imap4.sln.metaproj : error MSB3202: The project file > "d:\a\1\s\packages\System.Net.Imap4.0.1.0..\example\example.csproj" was not found. [d:\a\1\s\packages\System.Net.Imap4.0.1.0\System.Net.Imap4.sln] Project "d:\a\1\s\packages\System.Net.Imap4.0.1.0\System.Net.Imap4.sln" (1) is building "d:\a\1\s\packages\System.Net.Imap4.0.1.0\System.Net.Imap4.csproj"

In the IMAP4 library, it specifically says that the following file was not found. When I added the package through Nuget Package Manager it installed perfectly but does not download the mentioned file example/example.csproj in the packages/System.Net.Imap4.0.1.0 folder.

**System.Net.Imap4.0.1.0 package structure**

![2019-10-16_18h17_53](https://user-images.githubusercontent.com/7566850/66977298-0c782480-f0c3-11e9-82ab-c2dad8de3348.jpg)

**System.Net.Imap4.0.1.0/lib/net35** (inside the lib there are no files and it contains only net35 folder) 
![2019-10-16_18h21_02](https://user-images.githubusercontent.com/7566850/66977322-26b20280-f0c3-11e9-9537-3d3b6b0f7625.jpg)

**System.Net.Imap4.0.1.0/properties**

What I am missing here to build the project successfully?

Note: I tried to view the hidden files also but the example.csproj file was not found.

**Refer:** https://stackoverflow.com/a/58424627/4197679

**Comment by bizzehdee** [comment]
The library was using an ancient ,net version, i have updated to .net standard
